C = gcc
CFLAGS = -Wall -pthread

all: server client

server: server.c
	$(CC) $(CFLAGS) server.c -o server

client: client.c
	$(CC) $(CFLAGS) client.c -o client

run: server client
	gnome-terminal -- ./server
	sleep 1 # Laisser le temps au serveur de démarrer
	gnome-terminal -- ./client
	gnome-terminal -- ./client
	gnome-terminal -- ./client

clean:
	rm -f server client
